#############################################################################
# Makefile for building: Project
# Generated by qmake (2.01a) (Qt 4.4.3) on: Sat Dec 13 19:37:41 2008
# Project:  Project.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile Project.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,--no-undefined
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread -lcv -lhighgui -lcxcore
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Graphm.cpp \
		main.cpp \
		MinHeap.cpp \
		robotdialog.cpp \
		ShortestPath.cpp moc_robotdialog.cpp
OBJECTS       = Graphm.o \
		main.o \
		MinHeap.o \
		robotdialog.o \
		ShortestPath.o \
		moc_robotdialog.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		Project.pro
QMAKE_TARGET  = Project
DESTDIR       = 
TARGET        = Project

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_robotdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Project.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile Project.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Project.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Project1.0.0 || $(MKDIR) .tmp/Project1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Project1.0.0/ && $(COPY_FILE) --parents Distance.h Edge.h Graphm.h MinHeap.h robotdialog.h ShortestPath.h .tmp/Project1.0.0/ && $(COPY_FILE) --parents Graphm.cpp main.cpp MinHeap.cpp robotdialog.cpp ShortestPath.cpp .tmp/Project1.0.0/ && $(COPY_FILE) --parents robotdialog.ui .tmp/Project1.0.0/ && (cd `dirname .tmp/Project1.0.0` && $(TAR) Project1.0.0.tar Project1.0.0 && $(COMPRESS) Project1.0.0.tar) && $(MOVE) `dirname .tmp/Project1.0.0`/Project1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Project1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_robotdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_robotdialog.cpp
moc_robotdialog.cpp: ui_robotdialog.h \
		robotdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) robotdialog.h -o moc_robotdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_robotdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_robotdialog.h
ui_robotdialog.h: robotdialog.ui
	/usr/bin/uic-qt4 robotdialog.ui -o ui_robotdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

Graphm.o: Graphm.cpp Graphm.h \
		Edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Graphm.o Graphm.cpp

main.o: main.cpp robotdialog.h \
		ui_robotdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MinHeap.o: MinHeap.cpp MinHeap.h \
		Distance.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MinHeap.o MinHeap.cpp

robotdialog.o: robotdialog.cpp robotdialog.h \
		ui_robotdialog.h \
		Graphm.h \
		Edge.h \
		ShortestPath.h \
		MinHeap.h \
		Distance.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o robotdialog.o robotdialog.cpp

ShortestPath.o: ShortestPath.cpp ShortestPath.h \
		MinHeap.h \
		Distance.h \
		Graphm.h \
		Edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ShortestPath.o ShortestPath.cpp

moc_robotdialog.o: moc_robotdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_robotdialog.o moc_robotdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

