######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 21 13:51:08 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Distance.h Edge.h Graphm.h MinHeap.h robotdialog.h ShortestPath.h
FORMS += robotdialog.ui
SOURCES += Graphm.cpp main.cpp MinHeap.cpp robotdialog.cpp ShortestPath.cpp
